---
title: "Analyse factors"
author: "Ricardo Ramirez"
date: "7/23/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Decomposing factor information

We will associate each factor with conditions of interest and modularize the genes
into coordinated responses

```{r}
source("./MOFAcell/code/02.factorutils.R")
```

# Define the model to analyse

```{r}
model_outfile <- "./results/DCM_broad/MOFA_mcell/DCMBroad_model.hdf5"
model <- MOFA2::load_model(model_outfile)

pb_data <- readRDS("./data_HCMDCM/pb_red.rds")

out_alias <- "./results/DCM_broad/MOFA_mcell/factor_desc"
```

```{r}
sample_dict_red <- read_csv("./data_HCMDCM/meta_data.csv")[,-1] %>%
  dplyr::rename("sample" = "donor_id")

meta <- sample_dict_red
```

# Factor 1

```{r}
summarize_factor(model = model,
                 factor = "Factor1",
                 pb_data = pb_data,
                 meta = meta,
                 covar = "disease",
                 out_alias = out_alias,
                 k = 8)
```

# Factor 2

```{r}
summarize_factor(model = model,
                 factor = "Factor2",
                 pb_data = pb_data,
                 meta = meta,
                 covar = "disease",
                 out_alias = out_alias,
                 k = 8)
```

# Factor 5

```{r}
summarize_factor(model = model,
                 factor = "Factor5",
                 pb_data = pb_data,
                 meta = meta,
                 covar = "disease",
                 out_alias = out_alias,
                 k = 5)
```



