---
title: "Calculate effective areas"
author: "Ricardo Ramirez"
date: "7/25/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

Once modules have been mapped it is time to calculate effective areas

```{r setup, include=FALSE}
library(tidyverse)
```

```{r}
process_modules <- function(module_file, sd_thrsh = 2) {
  
  module_mat <- read_csv(module_file,show_col_types = F) %>%
    as.data.frame()
  
  rownames(module_mat) <- module_mat[,1]
  
  module_mat <- module_mat[, -1]
  
  module_mat[module_mat < sd_thrsh] <- 0 
  
  n_spots <- nrow(module_mat)
  
  summ <- module_mat %>%
    as.data.frame() %>%
    rownames_to_column("spot_id") %>%
    pivot_longer(-spot_id) %>%
    dplyr::mutate(n_spots = n_spots) %>%
    group_by(name) %>%
    mutate(n_module = map_lgl(value, ~ .x != 0) %>%
             sum()) %>%
    dplyr::filter(value != 0) %>%
    mutate(mean_module = mean(value)) %>%
    dplyr::select(name, n_module, mean_module, n_spots) %>%
    unique() %>%
    mutate(area = n_module/n_spots,
           w_area = (n_module/n_spots) * mean_module)
  
  return(summ)
    
}
```

# Define list of files

```{r}
annotation_names <- tibble(patient_group = c("group_1", 
                                             "group_2", 
                                             "group_3"),
                           patient_group_name = c("myogenic-enriched", 
                                                  "ischemic-enriched", 
                                                  "fibrotic-enriched"))

meta <- read_csv("./data_MI/visium_patient_anns_revisions.csv") %>%
  left_join(annotation_names)
 
```

```{r, message=F}
dir <- "./results/MOFA_mcell/factor_desc/Factor3_char/decoupler/"

samples <- list.files(dir)

samples <- set_names(paste0(dir,samples), gsub("[.]csv", "", samples))

area_summ <- map(samples, process_modules, sd_thrsh = 1) %>%
  enframe(name = "sample_id") %>%
  unnest() %>%
  dplyr::select(sample_id, name, area, w_area) %>%
  tidyr::complete(sample_id, name, fill = list("area" = 0,
                                                          "w_area" = 0)) %>%
  left_join(meta, by = "sample_id")
```

```{r}

area_summ %>%
  ggplot(aes(x = patient_group_name, y = w_area)) +
  geom_boxplot() +
  facet_wrap( ~ name, ncol = 3, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90))

```

